/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.89
 * Generated at: 2024-07-04 16:56:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.io.PrintWriter;
import bbs.BbsDAO;
import bbs.Bbs;
import java.util.ArrayList;

public final class bbs_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(4);
    _jspx_imports_classes.add("java.io.PrintWriter");
    _jspx_imports_classes.add("bbs.Bbs");
    _jspx_imports_classes.add("bbs.BbsDAO");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!--  게시판 -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--  게시판 --> \r\n");
      out.write("\r\n");
      out.write("<!--  게시판 --> \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<!-- Latest compiled and minified CSS -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css\" integrity=\"sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u\" crossorigin=\"anonymous\">\r\n");
      out.write("<!-- Optional theme -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap-theme.min.css\" integrity=\"sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp\" crossorigin=\"anonymous\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/bbsStyle.css\"> <!-- 외부 CSS 파일 참조 -->\r\n");
      out.write("<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.1.1.min.js\"></script>\r\n");
      out.write("<!-- Latest compiled and minified JavaScript -->\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js\" integrity=\"sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/jumbotronCustom.css\">\r\n");
      out.write("<title>JSP 게시판 웹 사이트</title>\r\n");
      out.write("<script>\r\n");
      out.write("	document.addEventListener('DOMContentLoaded', function() {\r\n");
      out.write("	    let sidebarHidden = false;\r\n");
      out.write("	\r\n");
      out.write("	    function adjustSidebar() {\r\n");
      out.write("	        var windowWidth = window.innerWidth;\r\n");
      out.write("	        var container = document.querySelector('.container');\r\n");
      out.write("	        var containerWidth = container ? container.offsetWidth : 0;\r\n");
      out.write("	        var sidebar = document.querySelector('.sidebar');\r\n");
      out.write("	        var mainContent = document.querySelector('.main-content');\r\n");
      out.write("	        \r\n");
      out.write("	        // 메인 콘텐츠와 사이드바가 겹칠 때 사이드바를 숨김\r\n");
      out.write("	        if (windowWidth <= containerWidth + 200 && !sidebarHidden) {\r\n");
      out.write("	            sidebar.classList.add('hidden');\r\n");
      out.write("	            mainContent.classList.add('expanded');\r\n");
      out.write("	            sidebarHidden = true;\r\n");
      out.write("	        } else if (windowWidth > containerWidth + 200 && sidebarHidden) {\r\n");
      out.write("	            sidebar.classList.remove('hidden');\r\n");
      out.write("	            mainContent.classList.remove('expanded');\r\n");
      out.write("	            sidebarHidden = false;\r\n");
      out.write("	        }\r\n");
      out.write("	    }\r\n");
      out.write("	\r\n");
      out.write("	    adjustSidebar();\r\n");
      out.write("	    \r\n");
      out.write("	    window.addEventListener('resize', function() {\r\n");
      out.write("	        adjustSidebar();\r\n");
      out.write("	    });\r\n");
      out.write("	});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");

    String userID = null;
    if (session.getAttribute("userID") != null) {
        userID = (String) session.getAttribute("userID");
    }
    int pageNumber = 1;
    if (request.getParameter("pageNumber") != null) {
        pageNumber = Integer.parseInt(request.getParameter("pageNumber"));  
    }
    String searchType = request.getParameter("searchType");
    String searchKeyword = request.getParameter("searchKeyword");
    String bbsCategory = request.getParameter("bbsCategory");
    
    // bbsCategory가 없으면 all로 설정
    if (bbsCategory == null || bbsCategory.equals("")) {
        bbsCategory = "all";
    }

    String categoryDisplayName = "";
    switch(bbsCategory) {
        case "all":
            categoryDisplayName = "전체글보기";
            break;
        case "free":
            categoryDisplayName = "자유게시판";
            break;
        case "study":
            categoryDisplayName = "공부게시판";
            break;
        case "exercise":
            categoryDisplayName = "운동게시판";
            break;
        default:
            categoryDisplayName = "기타";
            break;
    }

      out.write("\r\n");
      out.write("    <div class=\"sidebar\">\r\n");
      out.write("        <a href=\"main.jsp\" style=\"text-align: center;\" >메인</a>\r\n");
      out.write("        <div class=\"dropdown\">\r\n");
      out.write("            <a href=\"bbs.jsp?bbsCategory=all\" style=\"text-align: center;\" >게시판 <span class=\"caret\"></span></a>\r\n");
      out.write("            <ul class=\"dropdown-menu\">\r\n");
      out.write("                <li><a href=\"bbs.jsp?bbsCategory=all\" style=\"text-align: center;\">전체글보기</a></li>\r\n");
      out.write("                <li><a href=\"bbs.jsp?bbsCategory=free\" style=\"text-align: center;\">자유게시판</a></li>\r\n");
      out.write("                <li><a href=\"bbs.jsp?bbsCategory=study\" style=\"text-align: center;\">공부게시판</a></li>\r\n");
      out.write("                <li><a href=\"bbs.jsp?bbsCategory=exercise\" style=\"text-align: center;\">운동게시판</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("        <a href=\"planner/planner.jsp\" style=\"text-align: center;\">플래너</a>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"main-content\">\r\n");
      out.write("        <nav class=\"navbar navbar-default navbar-fixed-top\">\r\n");
      out.write("            <div class=\"container-fluid\">\r\n");
      out.write("                <div class=\"navbar-header\">\r\n");
      out.write("                    <button type=\"button\" class=\"navbar-toggle collapsed\" data-toggle=\"collapse\" data-target=\"#bs-example-navbar-collapse-1\" aria-expanded=\"false\">\r\n");
      out.write("                        <span class=\"sr-only\">Toggle navigation</span>\r\n");
      out.write("                        <span class=\"icon-bar\"></span>\r\n");
      out.write("                        <span class=\"icon-bar\"></span>\r\n");
      out.write("                        <span class=\"icon-bar\"></span>\r\n");
      out.write("                    </button>\r\n");
      out.write("                    <a class=\"navbar-brand\" href=\"main.jsp\">게시판 프로젝트</a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"collapse navbar-collapse\" id=\"bs-example-navbar-collapse-1\">\r\n");
      out.write("                    <ul class=\"nav navbar-nav\">\r\n");
      out.write("                        <li><a href=\"main.jsp\">메인</a></li>\r\n");
      out.write("                        <li class=\"dropdown active\">\r\n");
      out.write("                            <a href=\"bbs.jsp?bbsCategory=all\" role=\"button\" aria-haspopup=\"true\" aria-expanded=\"false\">게시판 <span class=\"caret\"></span></a>\r\n");
      out.write("                            <ul class=\"dropdown-menu\">\r\n");
      out.write("                                <li><a href=\"bbs.jsp?bbsCategory=all\">전체글보기</a></li>\r\n");
      out.write("                                <li><a href=\"bbs.jsp?bbsCategory=free\">자유게시판</a></li>\r\n");
      out.write("                                <li><a href=\"bbs.jsp?bbsCategory=study\">공부게시판</a></li>\r\n");
      out.write("                                <li><a href=\"bbs.jsp?bbsCategory=exercise\">운동게시판</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li><a href=\"planner/planner.jsp\">플래너</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                    ");
 if(userID == null) { 
      out.write("\r\n");
      out.write("                        <ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("                            <li class=\"dropdown\">\r\n");
      out.write("                                <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\" role=\"button\" aria-haspopup=\"true\" aria-expanded=\"false\">접속하기 <span class=\"caret\"></span></a>\r\n");
      out.write("                                <ul class=\"dropdown-menu\">\r\n");
      out.write("                                    <li><a href=\"id/login.jsp\">로그인</a></li>\r\n");
      out.write("                                    <li><a href=\"id/join.jsp\">회원가입</a></li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    ");
 } else { 
      out.write("\r\n");
      out.write("                        <ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("                            <li class=\"dropdown\">\r\n");
      out.write("                                <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\" role=\"button\" aria-haspopup=\"true\" aria-expanded=\"false\">회원관리 <span class=\"caret\"></span></a>\r\n");
      out.write("                                <ul class=\"dropdown-menu\">\r\n");
      out.write("                                    <li><a href=\"id/profile.jsp\">My Profile</a></li>\r\n");
      out.write("                                    <li><a href=\"id/logoutAction.jsp\">로그아웃</a></li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    ");
 } 
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </nav>\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"category-title\">\r\n");
      out.write("                    ");
      out.print( categoryDisplayName );
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("                <form class=\"form-inline\" method=\"get\" action=\"bbs.jsp\">\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <select class=\"form-control\" name=\"searchType\">\r\n");
      out.write("                            <option value=\"title\" ");
      out.print( "title".equals(searchType) ? "selected" : "" );
      out.write(">제목</option>\r\n");
      out.write("                            <option value=\"content\" ");
      out.print( "content".equals(searchType) ? "selected" : "" );
      out.write(">내용</option>\r\n");
      out.write("                            <option value=\"writer\" ");
      out.print( "writer".equals(searchType) ? "selected" : "" );
      out.write(">작성자</option>\r\n");
      out.write("                        </select> \r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <input type=\"text\" class=\"form-control\" name=\"searchKeyword\" placeholder=\"검색어를 입력하세요\" value=\"");
      out.print( (searchKeyword != null && !searchKeyword.equals("")) ? searchKeyword : "" );
      out.write("\" style=\"width: 400px;\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <input type=\"hidden\" name=\"bbsCategory\" value=\"");
      out.print( bbsCategory );
      out.write("\">\r\n");
      out.write("                    <button type=\"submit\" class=\"btn btn-default\">검색</button>\r\n");
      out.write("                </form>\r\n");
      out.write("                <table class=\"table table-striped\" style=\"text-align: center; border: 1px solid #dddddd\">\r\n");
      out.write("                    <thead>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <th class=\"number-col\" style=\"background-color: #eeeeee; text-align: center;\">번호</th>\r\n");
      out.write("                            <th class=\"title-col\" style=\"background-color: #eeeeee; text-align: center;\">제목</th>\r\n");
      out.write("                            <th class=\"writer-col\" style=\"background-color: #eeeeee; text-align: center;\">작성자</th>\r\n");
      out.write("                            <th class=\"date-col\"style=\"background-color: #eeeeee; text-align: center;\">작성일</th>\r\n");
      out.write("                            <th class=\"viewCount-col\"style=\"background-color: #eeeeee; text-align: center;\">조회수</th>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                    </thead>\r\n");
      out.write("                    <tbody>\r\n");
      out.write("                        ");
 BbsDAO bbsDAO = new BbsDAO();
                           ArrayList<Bbs> list;
                           int totalPage;
                           if (searchKeyword != null && !searchKeyword.equals("")) { // 검색어가 있을 때
                               list = bbsDAO.searchList(pageNumber, searchType, searchKeyword, bbsCategory);
                               totalPage = (bbsDAO.getSearchPostCount(searchType, searchKeyword, bbsCategory) + 9) / 10; // 검색 결과의 총 페이지 수 계산
                           } else { // 검색어가 없을 때
                               if ("all".equals(bbsCategory)) { // 전체게시판 선택 시
                                   list = bbsDAO.getAllList(pageNumber);
                                   totalPage = bbsDAO.getTotalPageCount(); // 전체 게시물의 총 페이지 수 계산
                               } else {
                                   list = bbsDAO.getListByCategory(bbsCategory, pageNumber);
                                   totalPage = bbsDAO.getTotalPageCountByCategory(bbsCategory); // 카테고리별 게시물의 총 페이지 수 계산
                               }
                           }
                           for(int i = 0; i < list.size(); i++) {
                        
      out.write("\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td>");
      out.print( list.get(i).getBbsID() );
      out.write("</td> \r\n");
      out.write("                                <td><a href=\"view.jsp?bbsID=");
      out.print( list.get(i).getBbsID() );
      out.write("&bbsCategory=");
      out.print( bbsCategory );
      out.write('"');
      out.write('>');
      out.print( list.get(i).getBbsTitle() );
      out.write("</a></td>\r\n");
      out.write("                                <td>");
      out.print( list.get(i).getUserID() );
      out.write("</td>\r\n");
      out.write("                                <td>");
      out.print( list.get(i).getBbsDate().substring(0, 11) + list.get(i).getBbsDate().substring(11,13) + "시" + list.get(i).getBbsDate().substring(14, 16) + "분" );
      out.write("</td>\r\n");
      out.write("                                <td>");
      out.print( list.get(i).getViewCount() );
      out.write("</td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                        ");
 } 
      out.write("\r\n");
      out.write("                    </tbody>\r\n");
      out.write("                </table>\r\n");
      out.write("                <div style=\"text-align: center;\">\r\n");
      out.write("                    ");
 
                        int pageBlock = 5;
                        int startPage = ((pageNumber - 1) / pageBlock) * pageBlock + 1;
                        int endPage = startPage + pageBlock - 1;

                        if(pageNumber != 1) {
                    
      out.write("\r\n");
      out.write("                        <a href=\"bbs.jsp?pageNumber=");
      out.print( pageNumber - 1 );
      out.write("&searchType=");
      out.print( searchType );
      out.write("&searchKeyword=");
      out.print( (searchKeyword != null && !searchKeyword.equals("")) ? searchKeyword : "" );
      out.write("&bbsCategory=");
      out.print( bbsCategory );
      out.write("\" class=\"btn btn-default pull-left\">이전</a>\r\n");
      out.write("                    ");
 } 
                        for (int i = startPage; i <= endPage && i <= totalPage; i++) {
                    
      out.write("\r\n");
      out.write("                        <a href=\"bbs.jsp?pageNumber=");
      out.print( i );
      out.write("&searchType=");
      out.print( searchType );
      out.write("&searchKeyword=");
      out.print( (searchKeyword != null && !searchKeyword.equals("")) ? searchKeyword : "" );
      out.write("&bbsCategory=");
      out.print( bbsCategory );
      out.write("\" class=\"btn ");
      out.print( (i == pageNumber) ? "btn-primary pull-left" : "btn-default pull-left" );
      out.write('"');
      out.write('>');
      out.print( i );
      out.write("</a>\r\n");
      out.write("                    ");
 } 
                        if(pageNumber != totalPage) {
                    
      out.write("\r\n");
      out.write("                        <a href=\"bbs.jsp?pageNumber=");
      out.print( pageNumber + 1 );
      out.write("&searchType=");
      out.print( searchType );
      out.write("&searchKeyword=");
      out.print( (searchKeyword != null && !searchKeyword.equals("")) ? searchKeyword : "" );
      out.write("&bbsCategory=");
      out.print( bbsCategory );
      out.write("\" class=\"btn btn-default pull-left\">다음</a>\r\n");
      out.write("                    ");
 } 
      out.write("\r\n");
      out.write("                    <a href=\"write.jsp?bbsCategory=");
      out.print( bbsCategory );
      out.write("\" class=\"btn btn-primary pull-right\">글쓰기</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
